upstream bookmark_service {
    server bookmark_service:8080;
}

upstream portal{
    server portal:3000;
}

limit_req_zone $binary_remote_addr zone=api_limit:10m rate=10r/m;

server {
    listen 80;
    listen [::]:80;
    server_name localhost;

    location /api/bookmark_service/ {
        proxy_pass http://bookmark_service/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;

        limit_req zone=api_limit burst=10 nodelay;
        limit_req_status 429;
    }

    location / {
    proxy_pass http://portal/;
    }
}