upstream bookmark_service {
    server bookmark_service:8080;
}

upstream portal{
    server portal:3000;
}


server {
    listen 80;
    server_name localhost;

    location /api/bookmark_service/ {
        proxy_pass http://bookmark_service/;
    }

    location / {
    proxy_pass http://portal/;
    }
}